name: Deploy to Github Pages

on:
  push:
    branches:
      - main    # 当推送到 main 分支时触发此工作流
jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许工作流写入仓库内容
      pages: write    # 允许工作流管理 GitHub Pages 部署
      id-token: write # 允许工作流获取 OIDC ID token，这是 actions/deploy-pages 所需的
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Npm install, build
      run: |
        npm install
        npm run docs:build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .vitepress/dist
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      
